SoCo/SoCo

soco/core.py
The multicast TTL may have value in [0, 255], which fits in one byte. Linux allows an 32-bit integer to be passed if its value is less than 256. Some `setsockopt` implementations (like OpenBSD), though, are less tolerant and require the input to actually be one byte long.
=> make the value of the IP_MULTICAST_TTL option one byte long

examples/plugins/socoplugins.py, soco/__init__.py, soco/alarms.py, soco/core.py, soco/discovery.py, soco/events.py, soco/services.py, unittest/test_events.py
Tidying up some odd and ends.
- remove code which has been deprecated for more than three releases
- move discover to its own module.  Note that `from soco import discover` will work just as it did before.
- slightly saner debug logging (clarified a few messages, removed pointless ones etc)
=> New year tidy

soco/discovery.py
This is based on ideas in #242. It allows an interface address to be specified when using discovery.  Unlike #242 however it requires the user of the SoCo library to specify the interfaces to be used, rather than using the netifaces module to find all the interfaces on the local machine.  This makes the code rather more simple, avoids the need for a dependency, and makes the user responsible for working out which interfaces to use based on knowledge of his or her system.
Thanks to @trollkarlen
=> Allow specification of discovery interface. Closes #242

soco/core.py
When streaming from a Tune In Radio station, anyway,
there might be nothing in the streamcontent but
still a title element.
=> Try a little harder to find a title for a stream

soco/config.py, soco/events.py
For cases where two independent processes on the same machine both want to listen to SONOS events.
=> Configurable event listener port

soco/data_structures.py
When I tried to add a uri to queue with python 3 I encountered an error (that the object returned by to_didl_string has no encode method) that suggested that to_didl_string does in fact not return a unicode string in python 3 the way the docstring says. I fixed this by adding the `encoding='unicode'` argument to `xml.etree.ElementTree.tostring` when on Python 3.
I guess this means I'm the only who has ever used SoCo on Python 3 since the new data structures, which is kind of disappointing :P for a big py3 proponent as me.
=> Make sure to_didl_string returns unicode also on python 3

soco/core.py, unittest/test_core.py
This is the PR that should fix issue #308. I merely change the implementation of the method to reflect the new data structures by essentially copying the implementation of add_to_queue.
This PR also removes a do-nothing-line from add_to_queue that was left after the fix in #306. At first I didn't understand why it even worked. In #306 I made sure that to_didle_string always returns a unicode object, the way its docstring suggests it should. But then I actually thought that the service call always wanted utf-8, because that is what is needed for the XML, so I was very surprised that the encoded version of the metadata was not assigned to anything and therefore not used. Then I checked up on and as it turns out the service calls does expect unicode (the way we originally decided, decode …
=> Iss308 fix add item to sonos playlist after data structure refactoring

soco/core.py, soco/exceptions.py, unittest/test_core.py
This is my attempt to solve the problem of calling master-only methods on a slave. It fixes this along the lines of option 2 as discussed here https://github.com/SoCo/SoCo/issues/138#issuecomment-44221244 by @lawrenceakka (Raises SoCoSlaveException when calling a master command on a slave). It is implemented as a decorator should be used to decorate all the master only methods in SoCo (of course it might it might turn out to be better to reverse the logic if there are many more master-only than master-and-slave method).
Right now it is only implemented on the play and pause method, because I wanted to get some input about whether you like this approach or not, before I start testing all the methods in SoCo for whether they can be called on a slave.
Please also have a look at the test …
=> Only on master

doc/releases/0.11.rst, doc/releases/index.rst
I've collected the release notes for the upcoming 0.11 release (see #278 and #261).
Please let me know if I forgot anything, or if my wording needs to be improved.
/cc all contributors to the release @simonalpha @trollkarlen @lawrenceakka @dajobe @robwebset @gutworth @poirier @michaelotto @hildroid @KennethNielsen
=> Add release notes for SoCo 0.11

setup.py
Reading of ``README.rst`` in ``setup.py`` can fail if the system's default encoding is not UTF-8 (#312). This pull request fixes this by explicitly specifying the encoding.
As the ``open`` builtin in Python 2.x does not have an encoding parameter, ``io.open`` is used as a compatible alternative.
=> Fix setup.py with non-UTF-8 encoding (fixes #312)

doc/data-structures-mod.rst, doc/unittests.rst
This PR aims to fix #319 by adding information about how to make the SoCo package importable from the git archive in a virtual environment.
=> Issue 319 missing documentation about python path for unittest

soco/data_structures.py
I was seeing exceptions like "soco.exceptions.DIDLMetadataError: Unknown UPnP class: object.item.audioItem" when subscribing to events.
Fixing the capitalization of DidlAudioItem's item_class member fixed it for me.
=> Fix capitalization of object.item.audioItem

soco/core.py, unittest/soco_unittest.py, unittest/test_core.py
Updated the ```get_speaker_info()``` function to parse ```xml/device_description.xml``` as described in #320
- changed zone_icon to player_icon
- added model_number
- added model_name
- added display_version
No unit tests yet
=> Preliminary speaker info with more information

soco/core.py, soco/music_library.py
`core.py` is getting very large indeed (see #127). I find it very hard to navigate, and increasingly confusing. It is unclear for new users that some functions, e.g. `get_artists` work only on the music library, and not on music services such as Spotify. I propose that we move all the music library related features to their own module.  This takes about 500 lines out of core.  
Instead of `device.get_album_artists()`, you will have to use `device.music_library.get_album_artists()` etc.
To me, this makes it much clearer which methods relate to the music library.  This PR achieves this but keeps the old methods in place (marked as deprecated).  I have not updated any docs (yet).
What do people think?
We might also consider moving radio related functions to a radio module, and perhaps queue …
=> Moving music library functions to own module

soco/music_services/music_service.py
This is just a minor bugfix to the music services code. The xmltodict.parse returns an ordereddict and asking it for its values on python2 return a list but on python3 returns a valuesview. The latter does not support indexing, so simply turn it into a list first.
=> Minor fix because ordereddict.values in py3 return ValuesView

README.rst
It took me some searching around to discover that you have the Sphinx docs built there. Was very handy, since the README examples are very vague for more advanced features - like getting radio stations. Why not link to it then? :smile:
=> link to readthedocs from the README

soco/compat.py, soco/ms_data_structures.py, soco/plugins/__init__.py, soco/plugins/spotify.py, soco/xml.py
It seems there is a new pylint in town, and its out to clean up the stre... code.
Joking aside. Fixes for new pylint warnings. Most are actually disables, either for legitimate reasons or because they were in more of less obsolete code like ms_data_structures or the old spotify plugin.
I consider this a minor fix, so I will merge immediately. Just posting it here for reference.
Any pull requests with failing Travis CI checks can rebase of master after I have merged.
=> Pylint fixes for new version

soco/alarms.py, soco/core.py, tests/test_core.py
As of version 6.0, Sonos supports playmodes REAPEAT_ONE and SHUFFLE_REPEAT_ONE (http://www.sonos.com/software/release/6-0).
The commits add the new playmodes to soco/alarms.py, soco/core.py, and tests/test_core.py.
=> Add playmodes REPEAT_ONE and SHUFFLE_REPEAT_ONE 

soco/services.py, soco/xml.py, tests/test_services.py
Apparently, certain radio stations sometimes sends invalid XML in the form of XML with disallowed characters in it (#386). This PR attempts for fix that. If the XML parsing in services.unwrap_arguments fail, we now try to filter out disallowed chars and retry the parsing.
I consider this a bug fix, so I will merge within a couple of days if there are no objections.
=> Filter invalid chars in xml fixes

soco/alarms.py
Required import of soco module not included, and would be masked regardless due to soco variable in function scope. Submodule import included instead.
=> Fix any_soco call in get_alarms

doc/tutorial.rst, examples/webapp/README.md
The remaining links to rahims/Soco appear to be ok. One is to the
original repository in the README, the rest are to historic issues.
=> Updated links to point to SoCo/Soco repository

soco/data_structures.py, tests/test_new_datastructures.py
Several music services seem to use a scheme for subclassing Didl classes by writing a subclass after the real class separated by .# e.g. object.container.album.musicAlbum.#AlbumView. This is not part of the Didl spec and so our implementation fails. This commit fixes this by stripping the sub-class, hence completely ignoring it. Fixes #399 and #388.
If anyone ever needs this information it should be simple enough to store it on the object while still using the real Didl class.
I consider this a bugfix, so it could be pulled without review, but since this has a bit of a design component to it, I though I would make a PR anyway. Also to allow the bug reporters to try the fix.
=> Ignore .# specified subclasses in Didl xml

soco/discovery.py
Depending on DNS configuration, gethostbyname() might return an address
that's not actually associated with the current host. In that case, just
log a warning and move on since the system default address will probably
work fine.
This fixes a regression introduced by
dfda28558cd571feeaa64367d126823d9a09f3db
=> Catch discovery socket exceptions, fixes #431.

soco/plugins/spotify.py
This PR is for the hard deprecation of the Spotify plugin. By hard deprecation I mean replacing all the code in the module with a RuntimeError describing the situation. The API docs will also show the text from the error.
The reason for this move is that the metadata API from Spotify, that this was originally written for, has reached end-of-life (see #401 for details). Given that we now have general code in the music_services sub-package that makes it possible to search Spotify, I think it is better to focus on that.
If anyone wishes to bring the dedicated plugin up to date with the newer  API (and fix a few bugs) then they can always pull it out of git.
In any case, as the current state of things are, the plugin is completely broken and we have a substitute, so I proposed this hard …
=> Hard deprecation of spotify plugin. Fixes #401.

soco/events.py
EventListener.start would sometimes blow up if attempting to subscribe to multiple services from different threads. This happens when for example you have a thread per-speaker subscribing to events. This also fixes a thread crash that would occur when receiving events that you have not subscribed for (no service for sid). This may happen when restarting applications based on SoCo.
=> Event listener thread safety

soco/data_structures.py
Ran into a problem when subscribing to events on avTransport:
Traceback (most recent call last):
File "/usr/lib/python3.4/socketserver.py", line 613, in process_request_thread
self.finish_request(request, client_address)
File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib/python3.4/socketserver.py", line 669, in __init__
self.handle()
File "/usr/lib/python3.4/http/server.py", line 398, in handle
self.handle_one_request()
File "/usr/lib/python3.4/http/server.py", line 386, in handle_one_request
method()
File "/usr/lib/python3.4/site-packages/soco/events.py", line 227, in do_NOTIFY
variables = parse_event_xml(content)
File "/usr/lib/python3.4/site-packages/soco/events.py", line 130, in parse_event_xml …
=> Added support for sonos playlist container UPnP class

soco/core.py, tests/test_core.py
This is a fix for #434. It replaces 'https://' and 'http://' in the beginning of the uri that is requested to play with Sonos® own prefix 'x-rincon-mp3radio://'. This should not affect people using this method for playing other types of uris e.g. 'x-file-cifs://'.
Also the unittests are updated.
Comments/questions?
=> Replace http(s) prefix in URIs to play with x-rincon-mp3radio://. Fixes #434.

README.rst, soco/core.py, soco/exceptions.py
This PR adds night mode for Sonos players that support this feature. Night mode will make the dialogue more clear, while reducing the intensity of loud sounds.
https://sonos.custhelp.com/app/answers/detail/a_id/1959/~/improving-speech-clarity-and-night-time-listening-through-the-playbar
=> Add playbar night mode support

README.rst, soco/core.py, soco/exceptions.py
This PR adds dialog mode for Sonos players that support this feature. Dialog mode will make dialogue easier to hear, which can be especially useful during action movies.
https://sonos.custhelp.com/app/answers/detail/a_id/1959/~/improving-speech-clarity-and-night-time-listening-through-the-playbar
=> Add playbar dialog mode support

soco/core.py, soco/data_structures.py, soco/data_structures_entry.py, soco/events.py, soco/ms_data_structures.py, soco/music_library.py, soco/music_services/data_structures.py, soco/music_services/music_service.py, tests/test_music_service_data_structures.py
Ok, so I had a request for comments PR open for a while, but did not get any feedback, so I continued and finished the implementation.
The work includes complete test coverage but no docs yet. I wanted to see this in before I added to the docs.
Quick summary:
My initial purpose was:
1. To have data structures similar to the ones we have for music library items
i.e. that can be browsed and added as is to the queue.
2. To expose the metadata
3. (Optionally) To have the metadata in the correct types
Initially I was planning on doing only the minimal to get them queue-able
(1. and 2. and just one class with the type as a attribute), but it turned out
to be only very little extra work to get a fully spec[1] compliant
implementation with classes for all the types.
The work is based on the …
=> Datastructures for the music services

README.rst
Following the brief discussion in #464 I'm proposing changing the README to direct support requests to the Google group or IRC.
I also changed the first one line description, since it has been some time since SoCo was a "simple class".
Questions, comments?
=> Add support section to README and change one line description

soco/core.py
This PR adds a `SoCo.add_multiple_to_queue()` method, which takes a list of queueable items and adds them to the queue with a single request. For spec compatibility, it also has a `container` parameter, which should be the superordinate Didl container, but since it also works without a container, the default is None.
=> Add multiple items to queue

soco/data_structures.py
I have noticed that I use DidlObject.resources[0].uri quite often and it is also present in the SoCo code multiple times. Hardcoding the index [0] in so many places does not seem very good practice to me.
Therefore, I have added get_uri and set_uri methods to DidlObject as a shortcut.
=> Methods for DidlObject.resources[0].uri

soco/core.py, tests/test_core.py
This is a copy of #300 with the requested test case for the parameter.
Can someone please check my test code (it's my first test with Mock)?
=> Support to play line in from another Sonos player with test

soco/core.py
This PR adds optional `position` and `as_next` arguments to `add_uri_to_queue()` and `add_to_queue()` to specify at which position the item should be inserted into the queue and whether this item should be played next.
=> add_to_queue() at given position

doc/examples.rst, soco/discovery.py, tests/test_discovery.py
This PR adds a very simple `by_name` function to discovery that returns a device by its name.
```python
from soco.discovery import by_name
device = by_name("Kitchen")
```
I don't know why I haven't done this earlier, since the code that it contains, I have been writing by hand a lot of time while testing different things.
Let me know what you think.
=> Added by_name function to discovery, with test and doc changes

soco/__init__.py, soco/snapshot.py
Second attempt at pull request to fix #475 
This fixes a python 3 potential issue, and adds documentation to snapshot to explain it should only be used once as on re-use variables are not initialised.
=> Added one use documentation and fixed Python 3 portnetial issue

doc/faq.rst, examples/snapshot/basic_snap.py, examples/snapshot/multi_zone_snap.py
A documentation pull request as discussed - an area with frequent question.
Please check I have changed the faq.rst correctly - not used that before.
Added 2 examples of using snapshot - tested on python 2.7 and 3.5 - feel free to recommend changes.
Cheers David
=> Documnetation: snapshot FAQ and examples

soco/core.py
During a transition between states sonos can return `TRANSITIONING` for `current_transport_state`. This change is just to document the value.
=> Add `TRANSITIONING` to possible values in `current_transport_state`

soco/core.py, tests/test_core.py
#457 fixes bug, and enhances play_uri:
- changed code
- added tests for the new code
- provided detailed documentation in the doc string about playing streams. Note I have updated this from   the comments in #457 based on the terminology used in the Sonos API guide.
This gives the user control to force a stream to be played as a radio stream when it defaults to a track stream. Some streams will error if forced, and some must be forced, so the user needs to know what they are doing. 
The release code helps the user in certain circumstances by forcing http:// &  https:// to play as radio. This may or may not be what the user wants depending on the stream.  This help will now be removed so people may initially hit a few problems with current code, until they understand they have the choice …
=> allow choice of how to play streams in play_uri

.travis.yml, doc/advanced/topology.rst, setup.py, soco/__init__.py, soco/compat.py, soco/data_structures_entry.py, soco/events.py, soco/groups.py, soco/ms_data_structures.py, soco/music_services/accounts.py, soco/music_services/data_structures.py, soco/music_services/music_service.py, soco/plugins/example.py, soco/plugins/wimp.py, soco/services.py, soco/soap.py, soco/utils.py, soco/xml.py, tests/soco_unittest.py, tests/test_core.py, tests/test_integration.py, tests/test_ms_data_structures.py, tests/test_music_service_data_structures.py, tests/test_musicservices.py, tests/test_services.py, tests/test_soap.py, tests/test_xml.py
Fixes #325.
Split out from PR https://github.com/SoCo/SoCo/pull/523 ("Drop support for EOL Python 2.6 & 3.3, add support for 3.6") to allow more granular decision making.
=> Drop support for Python 2.6

soco/snapshot.py
Fixes way snapshot determines if device is coordinator. 
Previous method worked but appears to have created the odd error - see #519 
Don't understand why old approach sometimes failed, but this change uses the standard SoCo approach.
=> Change to use SoCo method to determine coordinator

.travis.yml, setup.py
Split out from PR https://github.com/SoCo/SoCo/pull/523 ("Drop support for EOL Python 2.6 & 3.3, add support for 3.6") to allow more granular decision making.
=> Add support for Python 3.6 and dev branches

soco/data_structures.py
This is a combined PR for #465 and #466 because both change the same code.
It fixes #458, #448 and #453.
=> Handle none values properly and fix avTransport events

pylintrc, soco/core.py, soco/data_structures.py, soco/music_library.py
This PR makes browsing Sonos favorites with the existing music library methods possible.
This is archieved by adding a data structure for the `object.itemobject.item.sonos_favorite` Didl class. The metadata of the favorites contains a `<resMD>`  tag, which encloses the metadata of the item to which the favorite refers. I have added a `reference` property to make this metadata accessible as a Didl object.
Unlike the existing implementation, one can now handle Sonos and radio favorites just like other music items - the specific methods are no longer required.
I would really like to integrate this functionality into SoCo, so please let me know if I should change something to get this merged!
=> Didl class for Sonos favorites

soco/core.py, soco/discovery.py, soco/plugins/wimp.py, soco/services.py, soco/soap.py
pylint has been updated on TravisCI, which means that currently the checks fail.
The new check, is one that checks for inconsistent return statements, basically, if there is an explicit return statement anywhere in a function, we should never rely on an implicite one (the `return None` that is always at the end of a function).
Therefore, this PR just adds a few explicit `return None` statements (and disables another warning in the wimp plugin, which should be deprecated soon anyway).
I'm merging immediately and posting here just for information. If you have string opinions against, let me know and we can revert.
=> Add explicit return statements to appease pylint

soco/core.py
This is a small bugfix to stop an error where None would be returned by metadata.findtext. Instead, an empty string is returned.
Closes #548.
=> Small bugfix in core.py

README.rst
The music service authentication issue tracked via #557 is quite serious and creating quite a bit of noise. This PR adds some information to the front page about, so as to hopefully make it easier for people to track and generate less duplicate issues.
=> Added information about the authentication issue to the front page readme

soco/events.py
I have experienced some inconsistent behavior during startup. This appears to be caused by a race in event registration: an event can come in before its handler is registered.
This PR corrects the issue by extending `_sid_to_service_lock` to cover the full registration.
That simple change is scary for two reasons:
1. The lock now covers a `requests.request` call that could take some time.
2. <s>It introduces nested locking with `_sid_to_event_queue_lock` so a deadlock could potentially happen down the road.</s> (now fixed, see comments)
A fix that addresses these issues will be more complex (which is also scary) but I will be happy to provide one if you prefer to avoid the drawbacks listed above.
=> Avoid lost events during subscription call

soco/events.py
This adds `__enter__` and `__exit__` methods to `Subscription`, to make the following idiom possible:
```python
with player.AVTransport.subscribe() as subscription:
event = subscription.events.get()
```
The subscription is automatically unsubscribed when exiting the `with` block.
=> Make Subscription a context manager

soco/events.py, soco/exceptions.py
This catches any exceptions thrown by `from_didl_string` during event handling. Instead a DidlFault is created, which rethrows the exception when the user tries to use it. This avoids an exception in the event thread, instead letting the user handle it when he needs the object. 
Compare with #568 for another implementation of the same proposal.
See #566 for information on why this is needed.
Closes #566, closes #568.
=> Delay object parsing exceptions, reraise on object use

soco/services.py, tests/test_services.py
This extends the services module in two ways:
- Handle default value / allowed value range in iter_actions and add a `__str__` function to the resulting Actions, to make the output more readable
- Allow keyword arguments in send_command, so you can do 
```python
renderingControl.SetRoomCalibrationStatus(RoomCalibrationEnabled=False)
```
instead of the less pythonic
```python
renderingControl.SetRoomCalibrationStatus([
('InstanceID', 0),
('RoomCalibrationEnabled', False)
])
```
to switch off Trueplay (something we do not yet support directly).
Let me know what you think of these extensions.
=> Services extensions

soco/core.py, tests/test_core.py, tests/test_integration.py, tests/test_music_library.py
Lots of methods were moved from core.py to music_library.py and scheduled for deprecation in the upcoming release 0.14 - this PR removes them as planned.
Closes #367.
=> Remove the methods that were deprecated in 0.12

soco/services.py, tests/test_services.py
#573 unadvertently made some breaking changes: See the discussion for #576.
This ensures backward compatibility for old calls of `send_command`.
`compose_args` is now only called if `args` is None.
=> Service extensions fix

soco/core.py
This is a bugfix for #397.
It makes all_groups, all_zones and visible_zones return copies of the current state, so the returned sets aren't modified later.
=> Fix mutating set from discover

soco/snapshot.py
This adds `__enter__` and `__exit__` methods to Snapshot, to make this idiom possible:
```python
with Snapshot(player):
player.play(something)  # e.g. announcement
time.sleep(10)
```
=> Make Snapshot a context manager

.travis.yml, doc/development/release-howto.rst
This pull request implements automatic deployment of tagged commits to PyPI.
The upload is triggered by Travis-CI. See [the documentation](https://docs.travis-ci.com/user/deployment/pypi/) for more information on this feature.
For this purpose I have created a new PyPI user `soco-bot`, and added it as a maintainer for the soco project there. Please let me know if I should add additional email addresses to this user, to avoid being the single point of failure for recovering access to the account.
This change would (slightly) reduce the effort of doing a release, and would lower the entry barrier for doing so.
=> Auto deploy new tagged releases to PyPI

.travis.yml, README.rst, setup.py
Fixes #525.
Split out from PR https://github.com/SoCo/SoCo/pull/523 ("Drop support for EOL Python 2.6 & 3.3, add support for 3.6") to allow more granular decision making.
Note: README.rst changes assumes #526 ("Drop support for Python 2.6") will be merged to prevent merge conflicts.
=> Drop support for Python 3.3

soco/core.py, soco/music_library.py
I checked the changes I made in #542 and adjusted all calls to the now-removed methods. This is based on @amelchio's work on #576.
Closes #576.
=> Fix what broke when the deprecated methods were removed

soco/alarms.py
I got this error:
```
/usr/local/lib/python3.5/dist-packages/soco/alarms.py in get_alarms(zone)
308         instance.enabled = values['Enabled'] == '1'
309         instance.zone = [z for z in zone.all_zones
--> 310                          if z.uid == values['RoomUUID']][0]
311         instance.program_uri = None if values['ProgramURI'] ==\
312             "x-rincon-buzzer:0" else values['ProgramURI']
IndexError: list index out of range
```
The problem is that some of my alarms have no rooms associated. This PR now skips all alarms with no associated room because in `save()` you do `self.zone.uid` which requires every room to have a zone. If you'd like to also allow alarms without zone, then please add a comment and I'll try to rework my PR.
=> don't throw exception if alarm is not associated to any room

soco/data_structures.py
A simple fix for #462.
DidlMusicAlbum now copies its _translation from its parent DidlAlbum instead of DidlAudioItem.
Closes #462.
=> Let DidlMusicAlbum copy _translation from DidlAlbum

soco/data_structures.py
The DidlObject hierarchy is missing a class for object.item.audioItem.audioBook.
This results in errors, as described in #616.
This PR creates the corresponding DidlAudioBook class, using the protocol information from page 155 of the [ContentDirectory spec](http://upnp.org/specs/av/UPnP-av-ContentDirectory-v2-Service.pdf).
Closes #616.
=> Added support for object.item.audioItem.audioBook

soco/data_structures.py
This PR turns Exceptions and ValueErrors which are raised in from_didl_string into DIDLMetadataErrors, allowing them to be caught in the event handling code. See [#567](https://github.com/SoCo/SoCo/pull/567#issuecomment-370102539) for why this is necessary.
=> Turn Exception in from_element and to_element into DIDLMetadataError

soco/services.py
This unconditional logging created noise for reasonable situations such as trying to skip the last track. Since we already raise an exception, just let the client decide how it should be handled.
=> Remove logging of UPnP failures

soco/data_structures.py
This adds a simple DidlPlaylistContainerTracklist class to data_structures.py. The class is used by Sonos when Sonos Speakers are controlled by Spotify Connect. The absence of the class from data_structures.py causes errors.
=> Add DidlPlaylistContainerTracklist to data_structures.py

soco/data_structures.py
This adds the object.item.audioItem.MusicTrack.RecentShow class to data structures. This is another non-UPnP-spec-compliant class which seems to be used for certain podcasts (see #655). This PR adds the class as outlined in that issue.
=> Add audioItem.MusicTrack.RecentShow to data structures (closes #655).

.travis.yml, soco/ms_data_structures.py, tests/conftest.py, tests/test_ms_data_structures.py, tests/test_new_datastructures.py
This is a simple PR to update the continuous integration environments after Python 3.8 was released. I also restricted the number of dev environments for stable Python versions to 2, to not over-use the ressource.
=> Update CI environments after release of Python 3.8

soco/data_structures_entry.py
This PR fixes an issue with a reduced amount of metadata for queue and
event items when upgrading them to their appropriate music service
type.
This should allow e.g. getting both title and album as properties and all remaining metadata from the DidlItem is available in the .metadata property of thr MusicService item.
Note. This PR is published as an alternative to #559. The reason for that is, that the music service data structures was added, since the music services use a completely different internal structure. In the long run, we want to be able to ask the music service to produce metadata for the MusicService items, including those coming from the queue. But until that has been implemented, we should preserve all the metadata we got.
Closes #535 and #559 and #547 and #552
=> Copy metadata from DidlItem to MusicServiceItem in get_queue and events

soco/core.py, tests/test_core.py
This PR adds the `set_relative_volume()` method to the `SoCo` class.
=> Adds the SoCo.set_relative_volume() method.

soco/__init__.py
As per #591 there no longer seems to be any opposition against deprecation of Python 2.7 in SoCo. This PR adds a deprecation warning stating that SoCo 0.19 will be the last version to support Python 2.7.
=> Add Python 2.7 deprecation warning

soco/core.py, soco/groups.py, tests/test_core.py
This PR adds group `volume` and `mute` properties, and the group `set_relative_volume()` method, to the ZoneGroup class.
=> Add group volume operations to SoCo

soco/data_structure_quirks.py, soco/data_structures.py
For a long time it has annoyed me, that I couldn't find a compromise I was happy with, between keeping the implementation of DIDL-Lite in data_structures.py specification compliant and at the same time allowing service specific fixes for non spec-compliant behavior. Now I have a proposal for one.
As is usually the case, I didn't make it up, but simply borrowed a solution for cleverer people. I think it was in the realm of graphics card drivers or 3D library implementations for games that I first heard of the idea of quirks, as a way of (separately) implementing exceptions for specific hardware or games that behaves differently from what they are supposed to and I thought that would be a good solutions for us.
In the long run, the idea is to pull the DIDL-Lite implementation in …
=> Beginning of data structure quirks, fix for missing protocolInfo

soco/data_structure_quirks.py
If protocol_info gets set manually we also have to make sure that
resource.text is defined otherwise we run into issues later on.
=> Fix quirks implementation

soco/core.py
Night mode and speech enhancement is supported by Sonos amp, but the amp is not listed in the code, meaning it is not supported at present.
=> Lists 'sonos amp' as a soundbar in order to provide night mode and speech enhancement support for amp.

tests/test_integration.py
Improve test_remove_playlist_bad_id() to accommodate the case of no existing playlists. Fixes #725.
=> Fix #725: Improve test_remove_playlist_bad_id()

pylintrc, requirements-dev.txt
All checks are currently failing due to the pylint update to v2.6. This PR suppresses two additional pylint warnings, allowing the checks to pass.
Also, the update to Black v20 flags multiple files for reformatting, hence failing the Black check. Pin Black to v19 for the time being.
=> Pin pylint to v2.5 and Black to v19, to avoid new warnings until after 0.20 release. 

pylintrc, requirements-dev.txt, soco/alarms.py, soco/cache.py, soco/core.py, soco/data_structures.py, soco/discovery.py, soco/events.py, soco/events_base.py, soco/events_twisted.py, soco/exceptions.py, soco/ms_data_structures.py, soco/music_services/accounts.py, soco/music_services/data_structures.py, soco/music_services/music_service.py, soco/plugins/example.py, soco/plugins/wimp.py, soco/services.py, soco/soap.py
This PR removes the Pylint version pin used in the checks, and eliminates the multiple instances of two new warnings that are reported under Pylint 2.6:
1. Removes 'super-with-arguments' warnings (R1725) by changing all `super()` invocations to Python 3 style.
2. Removes 'raise-missing-from' warnings (W0707) by adding `from <initial exception>` where required.
=> Unpin Pylint version and eliminate new warnings

README.rst
I'd like to add a link to the README for the `soco-cli` command line wrapper for SoCo. `soco-cli` is now fully-featured and quite stable.
Link: https://github.com/avantrec/soco-cli
=> Add reference to soco-cli in the README

soco/core.py
Hi,
I updated the documentation that was lacking the REPEAT_ONE and SHUFFLE_REPEAT_ONE play modes.
=> Updated documentation for core.play_mode to add REPEAT_ONE and SHUFFLE_REPEAT_ONE

soco/events.py
Python 3.9 checks are failing because `Thread.isAlive()` was deprecated in Python 3.8 and removed in Python 3.9. Replace with `Thread.is_alive()`.
=> Replace 'isAlive()' with 'is_alive()' for Python 3.9 compatibility

requirements.txt, soco/discovery.py, tests/test_discovery.py
This is a proof-of-concept to add a new discovery function `scan_network()` that detects Sonos devices by scanning all IPs on the networks to which the SoCo host is attached. I've added the function to the existing `discovery.py` file, but it is standalone and not integrated with the other discovery functions.
This is to circumvent situations where the network is not correctly passing multicast traffic, meaning that the normal discovery functions do not work.
It appears to work on Windows, macOS, and Linux hosts, although my testing has necessarily been restricted to a small number of networks. I'd welcome other people trying it out.
**Edit: The following no longer applies**: _(Like the existing discovery functions, this function is vulnerable to the situation where there are multiple …
=> Network Scan Discovery

soco/discovery.py, tests/test_discovery.py
This PR just adds the option to specify exactly which network(s) to scan, instead of depending on the default mechanism of interrogating the network adapters.
=> Network scan discovery: add ability to specify the network(s) to scan

soco/core.py
This PR addresses #723.
I've only tested against a Move on my S2 system, and there are indications that this approach doesn't work with S1 systems. It would be useful if someone could test this.
=> Add 'get_battery_info' method to the SoCo class

soco/core.py, soco/discovery.py, soco/services.py
I am trying to enable multi-household control. A blocker for this is that we currently maintain a global state cache that is invalid when a speaker from a different household is accessed.
This PR removes the global variable and makes the cache per-household.
I moved 10.0.2.14 ("Test") to a separate household. Before this PR:
```
$ python -c 'import soco; a = soco.SoCo("10.0.2.18"); b = soco.SoCo("10.0.2.14"); print(a.player_name); print(b.player_name);'
Kitchen
None
```
After this PR:
```
$ python -c 'import soco; a = soco.SoCo("10.0.2.18"); b = soco.SoCo("10.0.2.14"); print(a.player_name); print(b.player_name);'
Kitchen
Test
```
=> Make zone-group-state cache per-household

soco/discovery.py
This is a small change to allow the `scan_network_get_by_name()` search to be optionally constrained by household_id.
=> Add optional household_id to scan_network_get_by_name()

soco/discovery.py
Simple convenience function to use `scan_network()` to return any zone, optionally constrained by `household_id`.
=> Add 'scan_network_any_soco()' convenience function

soco/discovery.py, tests/test_discovery.py
This PR excludes any link local networks from `scan_network()` discovery. Windows systems seem to report these networks when their network interfaces are interrogated, but they don't need to be scanned.
=> Exclude link local networks from scan_network()

soco/core.py, soco/snapshot.py, tests/test_core.py
This PR adds a gettable/settable `fixed_volume` property to the SoCo class, with accompanying tests. It also adds a `supports_fixed_volume` property to determine if a device supports this feature.
This (currently) only applies to Sonos Connect and Sonos Port devices. All non-applicable devices raise a `NotSupportedException` on set attempts, and will always return `False` on gets.
Tested with both Sonos Connect (S1) and Sonos Port (S2), as well as with devices for which `fixed_volume` is non-applicable.
=> Add a 'fixed_volume' property to the SoCo class

soco/core.py, soco/services.py
This PR adds the definitions so that the AudioIn service is created. This allows one to obtain the names of the inputs and to register for notification of active inputs.
=> Add AudioIn Service

soco/core.py, soco/exceptions.py, tests/test_core.py
This PR adds a gettable/settable `buttons_enabled` property to the SoCo class, including accompanying tests.
Note that this inverts the function of the underlying `deviceProperties.ButtonLockState*` operations. I think it's more meaningful to deal with buttons that are enabled or disabled, rather than locked or unlocked.
Can only be set on visible speakers, or an exception (`SoCoNotVisibleException`) is raised. Applying to non-visible speakers does 'interesting' things, and probably not what's desired.
Tested on S1 and S2 devices, with and without control buttons. For devices without buttons (e.g., Sonos Port) the operations still succeed and don't appear to have any effect nor to do any harm.
=> Add a 'buttons_enabled' property to the SoCo class

soco/discovery.py, tests/test_discovery.py
This PR changes the way that `discover()` determines the IP addresses to use for multicast discovery. It replaces the use of `gethostbyname()` with a comprehensive list of IPv4 addresses obtained using the `ifaddr` library. This should cover cases where the host has multiple NICs and/or multiple IP addresses associated with those NICs, and prevent some of the common problems encountered when using discovery. 
Addresses #764.
=> Improve discover(): perform discovery on all NICs/IPs

soco/core.py, tests/test_core.py
This PR adds a gettable/settable property `trueplay`, with accompanying tests. The property allows the Trueplay state of a speaker (`True` or `False`) to be determined, and to be changed.
Devices that do not support Trueplay, or which do not have  a current Trueplay calibration, will return `None` on getting the property, and  raise a `NotSupportedException` when setting the property. Can only be set on visible devices. Attempting to set on non-visible devices will raise a `SoCoNotVisibleException`.
Tested on S1 and S2 devices, devices that don't support Trueplay, and devices that do support Trueplay, with and without a current calibration profile.
=> Add 'trueplay' property to SoCo

soco/services.py
There is a small typo in soco/services.py.
Should read `unknown` rather than `unknonwn`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, unknonwn -> unknown

requirements-dev.txt, soco/core.py, tests/test_core.py
This is a much more efficient implementation of `get_battery_info()`, using a different speaker URL to get the battery status. Tests have been added. Note the additional requirement for the `requests-mock` library in order to run the tests.
=> Improve efficiency of 'get_battery_info()' and add tests

.travis.yml, doc/releases/0.21.rst, doc/releases/index.rst, soco/__init__.py
**Note**: this PR will be merged when v0.21 is ready for release.
- Increment version number to 0.21
- Add release notes for v0.21
- Remove 'deploy' section from .travis.yml
=> Release v0.21 preparation

tests/test_core.py, tests/test_integration.py, tests/test_music_library.py
Pytest 6.2 introduced some new deprecation warnings for the use of `@pytest.yield_fixture()`. Replace every instance with `@pytest.fixture()`, which does the same thing (according to pytest).
=> Squash '@pytest.yield_fixture()' warnings in Pytest 6.2+

soco/snapshot.py
Due to races, our idea of a speaker being a coordinator could be wrong. In that case, restoring its queue will fail. This PR ensures that this failure does not keep the volume from being restored.
I have split this change into three commits to make it easier to review.
=> Always restore volume

soco/core.py
We currently reload the zone group cache after group changes (join/unjoin). As this is a synchronous operation, it actually slows the client down.
If we end up using the cache, the time we save has already been spent filling it. If we do not use the cache within 5 seconds, filling it was redundant.
Also note that group changes often happen to multiple speakers in turn and we are currently reloading the cache after each such operation.
So it seems that _not_ reloading the cache is always at least as good. Thus, this PR removes the preloading.
=> Do not refresh zone group cache on join/unjoin

soco/events_base.py
This keeps our event thread from dying due to uncaught exceptions in the client event handling code.
=> Catch client exceptions on event thread

soco/music_services/music_service.py
Introduces a step that cleans up the incorrectly parsed URL due to the breaking change in Python outlined in #810. Also works with earlier versions of Python that don't include the change.
=> Fix #810: Change in behaviour of urllib parse

soco/events.py, soco/services.py, tests/test_services.py
Add timeout values so network requests cannot hang indefinitely.
Also ignore a couple of error situations during unsubscribe because no error handling is needed in those situations.
These issues were found by running a network conditioner with pretty bad settings.
=> Improve handling of network errors

pylintrc
Note: false positives not seen on Ubuntu.
Mentioned in Pylint issues:
- https://github.com/PyCQA/pylint/issues/4300
- https://github.com/PyCQA/pylint/issues/4297
=> Suppress false-positive Pylint errors with Python 3.9 on macOS 11.0.

doc/advanced/events.rst, doc/advanced/events_asyncio.rst, doc/api/soco.events.rst, pylintrc, requirements.txt, soco/events_asyncio.py, soco/events_base.py
This is the module being used in Home Assistant and pysonos (https://github.com/amelchio/pysonos/blob/master/pysonos/events_asyncio.py) with the extras stripped out modified to work on python 3.5+.
=> Add asyncio events module

requirements.txt, setup.py, soco/events_asyncio.py
This PR removes the hard dependency on the `aiohttp` package, and introduces a descriptive error message if `events_asyncio` is imported but its `aiohttp` requirements are not satisfied.
The `aiohttp` package can be installed independently if required, or with SoCo by using:
`pip install "soco[events_asyncio]"`.
=> Workaround for #819

soco/events_asyncio.py
The current async events module does not actually raise `aiohttp` exceptions inside of `try:` blocks as the `raise_for_status` argument was missing. This can lead to problems such as failed subscription renewals being silently ignored.
=> Raise exceptions on aiohttp status in async event handler

soco/core.py
This adds extraction of `TYPE=SNG` metadata in radio streams. I don't know exactly which standard this is but it has been reported being using at least with SiriusXM and Apple Music.
The first commit moves the existing extraction into a dedicated function to avoid a too-many-branches Pylint warning.
=> Extract SNG metadata

soco/data_structures.py
This fixes #801 for me. I am still not quite sure what the intention is but having the two places use similar handling seems reasonable. The change has been in Home Assistant for a couple of months with no reported issues.
While at it, I have added handling of unofficial `#` subclasses (in addition to `.#`), originally implemented in https://github.com/swehog/pysonos/commit/6f78223d8d292d3179ba69eb4d0fd64906018506. This has also been in Home Assistant for a long time.
=> Ignore unofficial subclasses

soco/events_asyncio.py
The logging and exception handling was a bit noisy and redundant in the new async event handler.
This change will not make subscription auto-renew calls `strict`. This matches the behavior in `events_twisted.py`: https://github.com/SoCo/SoCo/blob/bb71285d5d9255a2eca942b357f292d613891f93/soco/events_twisted.py#L325-L329)
If a call to the `auto_renew_fail` callback is made, we will no longer log an exception traceback from `SoCo` as it's assumed the caller now has that information.
=> Cleanup async_events renewal logging and exceptions

soco/events.py, soco/events_asyncio.py, soco/events_base.py, soco/events_twisted.py, soco/services.py
This downgrades some logging statements so SoCo does not log above the DEBUG level in normal use.
A single log level has been increased since it could be a real problem (client code raising an exception while handling an event).
Some related discussion in #792.
=> Adjust log levels

soco/core.py, tests/test_integration.py
This adds a `get_current_media_info()` method which is very similar to `get_current_track_info()`, but for the `GetMediaInfo` service.
We are using this in Home Assistant to get the channel name when playing radio. The `uri` is useful for finding out whether a favorite is playing since it matches those, unlike `get_current_track_info()['uri']`.
No other information from `GetMediaInfo` seemed interesting, here is an example of the full data:
```
{'CurrentURI': 'x-sonosapi-stream:s216726?sid=254&flags=8224&sn=0',
'CurrentURIMetaData': '<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" '
'xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" '
'xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" '
'xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item '
'id="-1" parentID="-1" ' …
```
=> Add get_current_media_info() method to the SoCo class

soco/events.py, soco/events_asyncio.py, soco/events_base.py, soco/events_twisted.py
The currrent event handlers are not able to send unsubscription requests to speakers because of a logic issue. This can lead to unintentionally leaving subscriptions active.
This change defers the internal unsubscription cleanup steps until after the outbound request is sent. This is achieved by adding an `unconditional` parameter to each implementations' request handler which is called after any request is sent. Only the `unsubscribe` method uses this for now.
This is an updated PR of #841 which adds missing changes in the default event handler.
=> Fix event unsubscription logic v2

doc/api/soco.plugins.rst, doc/api/soco.plugins.sharelink.rst, soco/data_structures.py, soco/events.py, soco/plugins/sharelink.py
This is a different take on supporting music services. It is a bit rough so I placed it in a plugin.
The plugin allows playing from the "share links" that some music services provide. No authentication step is needed but the matching music service must be installed on Sonos. 
Supported link formats:
* `https://open.spotify.com/track/6cpcorzV5cmVjBsuAXq4wD`
* `spotify:album:6wiUBliPe76YAVpNEdidpY`
* `https://tidal.com/browse/album/157273956`
The constructed message data was found with Wireshark while pressing play in the native app. I have no idea what it means but it does work :). Adding other services is probably straightforward but it requires an active account in order to do the network dump.
There is a US and a non-US Spotify service so the service ID is looked up dynamically. I have …
=> Add plugin for playback of Spotify & Tidal ShareLinks

soco/core.py
Adjustment to https://github.com/SoCo/SoCo/pull/662 to preserve pre-10.1 compatibility without breaking current firmware versions.
Integrated in `pysonos` [here](https://github.com/amelchio/pysonos/pull/99) and now in use by the latest Home Assistant release.
Waiting for confirmation from the end-user before marking this ready for review.
=> Restore compatibility for Sonos firmware < v10.1

soco/services.py
As seen in https://github.com/home-assistant/core/issues/52716#issuecomment-884374637, Sonos Boost devices will reject certain service calls (e.g., `GetVolume`):
```
2021-07-21 13:09:00 DEBUG (SyncWorker_14) [pysonos.services] Dispatching method GetVolume
2021-07-21 13:09:00 DEBUG (SyncWorker_14) [pysonos.services] Sending GetVolume [('InstanceID', 0), ('Channel', 'Master')] to 192.168.0.34
2021-07-21 13:09:00 DEBUG (SyncWorker_14) [pysonos.services] Sending {'Content-Type': 'text/xml; charset="utf-8"', 'SOAPACTION': 'urn:schemas-upnp-org:service:RenderingControl:1#GetVolume'}, <?xml version="1.0" ?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<u:GetVolume …
```
=> Raise exception if Service command not supported

soco/events_asyncio.py, soco/events_base.py
If an unsubscription request fails, the `Subscription` object is not properly cleaned up. This can lead to dangling failed subscriptions which conflict with attempts to recreate new subscriptions.
The call to `_cancel_subscription` is currently called in request failure scenarios for both subscriptions and renewals, but not after unsubscription request failures:
https://github.com/SoCo/SoCo/blob/5602d2880af8a3daa9158a2982fca8130d41b13f/soco/events_asyncio.py#L367-L368
https://github.com/SoCo/SoCo/blob/5602d2880af8a3daa9158a2982fca8130d41b13f/soco/events_asyncio.py#L418-L419
=> Clean up subscription if unsubscription request fails

soco/core.py, tests/test_core.py
Having the boot sequence number on a zone can be useful for determining when a given zone has lost power or is otherwise rebooted. This information is available from SSDP & Zeroconf discovery broadcasts, but this is the only way I've been able to find it in direct queries to the speaker.
=> Add boot count attribute to zones

.github/workflows/soco-check-jobs.yaml
Instead of duplicating the test configs, loop through using a matrix and specific job exceptions.
Bumps the 3.10 version to the latest available, and also disables building docs on 3.10 as https://github.com/sphinx-doc/sphinx/issues/9505 is an open issue causing CI failures.
=> Use matrix in CI config

soco/alarms.py
When using the `soco.alarms` module in tandem with subscription callback events, I found it was difficult to know if the current state of the alarms was accurate. When an alarm is changed and events are sent out (from each speaker), it can take some time for updated alarms to propagate to all speakers. The `zone.alarmClock.ListAlarms()` call returns a `CurrentAlarmListVersion` which can be matched against the same one provided in the event payload, but this does not exist in the current implementation.
While adding support for this value, I found it was easier to think of things in terms of a parent storage class (`Alarms`) which contains all `Alarm` instances instead of using the `weakref` class attribute.
This PR adds new functionality while attempting to preserve existing behavior:
* …
=> Refactor alarm handling

soco/plugins/sharelink.py
I added a DeezerShare link interpreter for the plugin.
Seems to work for albums / playlists / tracks on my end. 
The sharelink is similar to a Spotify sharelink:
deezer:playlist:5390258182
=> Add Deezer support to the sharelink plugin

soco/data_structures_entry.py
The warnings for failed datastructure upgrades from DIDL -> MS can be a bit noisy. This was previously adjusted in https://github.com/SoCo/SoCo/pull/839.
This PR reinstates logging for ignored classes at debug level to assist troubleshooting and ignores two additional class names (`DidlItem` and `DidlPodcast`).
For context, the podcast upgrade warning was reported by a user playing from Pocket Casts via the Sonos app.
@KennethNielsen please say if you believe this may hide useful information.
=> Rework DIDL datastructure upgrade failure logging

soco/events_asyncio.py, soco/services.py, tests/test_services.py
This adjusts the `requests` and `aiohttp` timeouts in two places:
1. Reduce the default service call timeout to 5s from 20s, allow passing in a timeout per-call.
2. Set an explicit async event handler timeout instead of using the default of 300s. (https://docs.aiohttp.org/en/stable/client_quickstart.html#aiohttp-client-timeouts)
=> Adjust timeouts for services and async event handler

README.rst, soco/core.py
Implements new properties (`is_satellite`, `has_satellites`, `is_subwoofer`, `has_subwoofer`, `channel`) for home theater and sub-paired configurations. These are populated from the Zone group state cache.
Also adds `surround_enabled` and `sub_enabled` properties to obtain & control the respective "_Surround Audio > Surrounds_" and "_Sub Audio > Sub_" toggle switches.
~~Note: This PR was created without direct access to a sub, so a bit of testing would be appreciated.~~
Sub controls have been confirmed working by a user with a subwoofer.
=> Add sub & surround properties and controls

soco/core.py
Addresses an unrelated CI issue uncovered in https://github.com/SoCo/SoCo/pull/871.
Since `pylint` is not pinned to a specific version, a newer release has marked previously accepted code with a warning. CI pinning is included with https://github.com/SoCo/SoCo/pull/857 (and improved with https://github.com/SoCo/SoCo/pull/855) which would avoid shifting test requirements in the future.
=> Address new pylint issue

soco/services.py, tests/test_services.py
I've received several reports from users that previously working service calls are now timing out. This coincides with the reduction of timeout from 20s to 5s in #868. This PR retains the ability to set a timeout per-call but reverts the default timeout to 20s.
=> Revert service call timeout reduction

soco/core.py
~~Renames the `SoCo.dialog_mode` property to `dialog_level` to match both the service call and subscription event callback payload. Adds a compatibility shim to avoid breaking existing usage.~~
Adjusted to simply add a convenience property named `dialog_level` which wraps `dialog_mode`.
=> Add `dialog_level` convenience property to mirror `dialog_mode`

soco/core.py, tests/test_core.py
Adds controls to the TV Dialog Sync audio delay exposed for home theater devices.
Oddly, this value doesn't seem to update in the native Sonos app even when navigating away and back. However its value is correctly reflected in realtime from `renderingControl` subscription events as `audio_delay`.
=> Add audio_delay property for TV dialog sync.

soco/core.py
This fixes an assumption that there will always be a `title` element when parsing radio-like stations (e.g., anything without a specific duration).
Example traceback:
```
track_info = self.soco.get_current_track_info()
File "/usr/local/lib/python3.9/site-packages/soco/core.py", line 1813, in get_current_track_info
track.update(_parse_radio_metadata(metadata))
File "/usr/local/lib/python3.9/site-packages/soco/core.py", line 1803, in _parse_radio_metadata
if title in track["uri"] or title in urllib.parse.unquote(track["uri"]):
TypeError: 'in <string>' requires string as left operand, not NoneType
```
=> Fix error when radio title is missing

soco/core.py, tests/test_core.py
Adds a new read-only boolean property which reports the current state of the device's microphone. For devices without a microphone or where a voice service has not yet been configured, the return value will be `None`.
Modified the `ZoneGroupState` XML in the tests to mark two speakers as voice-enabled in order to allow testing this new feature. Should have no effect on existing tests.
=> Add `mic_enabled` property to the SoCo class

soco/config.py, soco/services.py
This is a possible approach to address the suggestion in the discussion around #876.
1. It moves the default timeout for requests to `config.py` in variable `config.REQUEST_TIMEOUT`. The default is set to 20.0s, as is currently the case. A value of `None` will establish an infinite timeout.
2. The value of `config.REQUEST_TIMEOUT` can be set dynamically at runtime.
3. It still permits the use of the `timeout` kwarg by callers, which will override the value in `config.REQUEST_TIMEOUT`.
=> Add configurable timeout for network requests

soco/core.py
Slight refactor to minimize the number of statements in `_parse_zone_group_state`. This may allow removal of the `pylint: disable=too-many-statements` pragma introduced in #879.
=> Refactor ZGS parsing; add `voice_service_configured` property

.pre-commit-config.yaml, dev_tools/analyse_ws.py, dev_tools/sonosdump.py, doc/conf.py, examples/play_local_files/play_local_files.py, makefile, setup.py, tests/test_core.py, tests/test_discovery.py, tests/test_events.py, tests/test_music_library.py, tests/test_music_service_data_structures.py, tests/test_musicservices.py, tests/test_new_datastructures.py, tests/test_singleton.py
pre-commit is the go-to method for making it simple to verify that all linters and other checks are performed before a commit can be done, or when executing `pre-commit run -a` manually. Having it in-place makes it easier to contribute without a need to wait for the CI to inform about styling issues.
This PR adds the same checks (black, pylint, flake8) as running `make` does (hopefully), but also removes the blanket ignores for blake8 and uses `# noqa: <id>` for two cases (import order for docs, unused variable for propertymocks for tests). This PR also includes the changes wanted by the checks that were not caught previously for some reason.
=> Add pre-commit hooks option; code/docstring tidy-ups

soco/data_structures_entry.py, soco/events_base.py
The `from_didl_string()` function is regularly called with the same input data when processing subscription events. By caching the results with `lru_cache`, we can avoid some processing overhead and also allow equality comparisons downstream for metadata as identical `DidlObject` instances are re-sent.
This uses the default size of 128 entries.
=> Use LRU caches for `from_didl_string` and `parse_event_xml`

soco/groups.py, tests/test_core.py
=> Add a 'SnapshotGroupVolume' operation before reading/changing group volume

soco/core.py
Report a new `music_source` value when playing via Spotify Connect (i.e., casting from the native Spotify app), similar to how AirPlay is reported.
=> Detect Spotify Connect as music source

soco/core.py
Some services (notably Sonos Radio) act as radio stations, but do not encode the current track's metadata in a `streamContent` element. This change will reprocess metadata if the radio decoding process does not populate the necessary fields.
Note: We only check if `artist` is empty as `title` is almost always set and `album` is less commonly provided. If `artist` is missing we can be fairly confident that it's worth reprocessing with the standard method.
=> Reprocess radio tracks if metadata incomplete

soco/music_services/music_service.py
Minor followup to #893 which prevents exceptions if the `.find()` calls do not succeed and return `None`.
Example traceback this PR addresses:
```python
>>> my_music_service.search("artists", "M83")
Traceback (most recent call last):
File "/src/SoCo/soco/music_services/music_service.py", line 199, in call
result_elt = message.call()
File "/src/SoCo/soco/soap.py", line 309, in call
raise SoapFault(faultcode, faultstring, faultdetail)
soco.soap.SoapFault: Client.TokenRefreshRequired: Token has expired
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/src/SoCo/soco/music_services/music_service.py", line 916, in search
response = self.soap_client.call(
File …
```
=> Check for empty token refresh to avoid exceptions

examples/play_local_files/play_local_files.py, soco/music_services/music_service.py
According to the [Sonos documentation](https://developer.sonos.com/reference/sonos-music-api/getdevicelinkcode/), the `loginToken` section is not required during the `POST` to get the `regUrl` and the `linkCode`.
Here is the working payload for `DeviceLink`:
```xml
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:s="http://www.sonos.com/Services/1.1">
<soap:Header>
<s:credentials>
<s:deviceId>XXX</s:deviceId>
<s:deviceProvider>Sonos</s:deviceProvider>
</s:credentials>
</soap:Header>
<soap:Body>
<s:getDeviceLinkCode>
<s:householdId>XXX</s:householdId>
</s:getDeviceLinkCode>
</soap:Body>
</soap:Envelope>
```
And for `AppLink`:
```xml
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:s="http://www.sonos.com/Services/1.1">
<soap:Header> …
```
=> Remove unnecessary `loginToken` during music service auth (fixes #891)

.pre-commit-config.yaml, soco/core.py, soco/services.py, tests/test_core.py, tests/test_musicservices.py
Adds following (setable) properties (see https://support.sonos.com/s/article/4804?language=en_US):
* ~~`surround_mode`: surround enabled/disabled~~ (already done in #870)
* `surround_ambient_enabled`: ambient/full volume in the music mode (bool)
* `surround_volume_tv`: surround volume adjustment [-15,15] for the tv mode (int)
* `surround_volume_music`: surround volume adjustment [15,15] for the music mode (int)
Currently missing reseting to defaults, and adjusting the surround speaker balance (which can only be done when trueplay is disabled, see https://github.com/SoCo/SoCo/pull/646#pullrequestreview-541049818).
Obsoletes #646. Fixes #461.
=> Add properties for surround speakers in TV, music and ambient modes

tests/conftest.py, tests/test_core.py, tests/test_music_library.py
Moves the redundant declarations of the `moco` fixture into `conftest.py`.
This was done in to prepare for a future test module which also needed the `moco` fixture.
=> Move mocked soco to conftest.py

soco/core.py, soco/utils.py, tests/data/media_metadata_payloads/bbc.json, tests/data/media_metadata_payloads/cifs.json, tests/data/media_metadata_payloads/pandora.json, tests/data/media_metadata_payloads/sonos_radio.json, tests/data/media_metadata_payloads/tunein.json, tests/test_metadata_parsing.py
A change in #896 caused certain titles (most obviously from CIFS shares) to be incorrectly discarded as they were contained in the track URI. This was naive as even single-word strings would trigger the discard behavior. This PR adds an additional hurdle which requires the track to contain some URI components before it is discarded, such as path and query arguments or an `.m3u8` extension.
I've also added tests to validate expected processing of metadata from a variety of sources. This should help ensure we're going all we can to get correct results and also prevent future regressions.
Note: This includes the commit from #904 in order to pass tests. Once that PR is merged this can be rebased to simplify the changes.
Fixes: #903
=> Check metadata title for URI hints before discarding

soco/core.py, tests/test_core.py
Reverses the boolean value to make it consistent with the eventing based value for easier integration for downstream users.
Example event (`surround_mode` is the variable in question, here shown in "full mode"):
```
{
"audio_delay" : "0",
"audio_delay_left_rear" : "1",
"audio_delay_right_rear" : "1",
"bass" : "0",
"dialog_level" : "0",
"headphone_connected" : "0",
"height_channel_level" : "0",
"loudness" : {
"Master" : "1"
},
"music_surround_level" : "6",
"mute" : {
"LF" : "0",
"Master" : "0",
"RF" : "0"
},
"night_mode" : "0",
"output_fixed" : "0",
"preset_name_list" : "FactoryDefaults",
"sonar_calibration_available" : "0",
"sonar_enabled" : "0",
"speaker_size" : "9",
"sub_crossover" : "0",
"sub_enabled" : "1",
"sub_gain" : "0",
"sub_polarity" : "0",
"surround_enabled" : "1", …
```
=> Rename `surround_ambient_enabled` to `surround_full_volume_enabled`

setup.cfg
When testing `isort` I noticed the `combine_star` config param had a typo: https://pycqa.github.io/isort/docs/configuration/options#combine-star.
=> Fix misnamed isort config param

soco/plugins/sharelink.py
Adds support for enqueuing podcast episodes and shows (i.e.., all episodes from a show) from Spotify URLs using `ShareLinkPlugin`. Although this does not seem supported from the Spotify music service interface in the native Sonos app, using base containers/classes seem to work fine.
=> Add support for Spotify podcast episodes/shows to ShareLinkPlugin

soco/plugins/plex.py
This adds two new features to the Plex plugin:
1. Allows inserting media into the queue at a specific index position.
2. Accepts lists of Plex media items to both `play_now()` and `add_to_queue()`.
The `add_next` parameter has been removed and `as_next` has been added instead. The `as_next` parameter will enqueue the item next in the queue _only_ if currently in shuffle mode. This matches the model used by `ShareLinkPlugin` and now relies on default Sonos behavior. As `position` is now exposed, it will be up to the user if they would like to enqueue media into the "next" playback position.
=> Handle lists of media in the Plex plugin; allow insertion by position

soco/core.py
Adds support for controlling the subwoofer gain using the `SoCo.sub_gain` property. This property name matches the key from the `RenderingControl` event payload.
Needs validation testing from a system that contains a subwoofer.
=> Add support for subwoofer gain controls

soco/core.py, soco/utils.py, tests/data/media_metadata_payloads/tunein_2.json, tests/test_metadata_parsing.py
Based on a new report, the logic added in #906 now seems overly specific. This adds an exception for CIFS tracks instead of validating the title as a URI fragment. All previous metadata processing results are unchanged and a newly added example now provides "correct" results.
=> Adjust metadata title discard logic

pylintrc, soco/alarms.py, soco/core.py, soco/data_structures.py, soco/discovery.py, soco/events.py, soco/events_asyncio.py, soco/events_base.py, soco/events_twisted.py, soco/ms_data_structures.py, soco/music_library.py, soco/music_services/accounts.py, soco/music_services/data_structures.py, soco/music_services/music_service.py, soco/plugins/plex.py, soco/plugins/wimp.py, soco/services.py, soco/snapshot.py, soco/soap.py, soco/utils.py
This updates the pylint configuration to disable more `too-many-*` checks and add comments with reasoning.
Also removes any existing pragmas in the codebase which match these new global disables.
=> Update pylint config, remove unnecessary pragmas

soco/plugins/plex.py, soco/plugins/sharelink.py
Allow passing `**kwargs` to the underlying service call for the ShareLink `add_share_link_to_queue()` and Plex `add_to_queue()` plugin methods. My primary reason is to allow differing `timeout` arguments for different services. Spotify, for example, seems to need a longer timeout when adding playlists with many tracks.
=> Pass kwargs for ShareLink/Plex queue methods

soco/core.py
I felt like the different Atmos codecs could use a little more specificity, but open to everyone's opinion!
Also added Dolby TrueHD 2.0 and DTS 5.1.
=> Add more detail on Dolby Atmos input formats

soco/core.py
Adds wrappers to the TV & music `surround_volume` properties to allow direct mapping to the native subscription event payload names.
A similar solution was previously implemented in https://github.com/SoCo/SoCo/pull/874.
=> Add convenience wrappers for surround_level properties

soco/core.py
A new release of `pylint` adds a new check: https://pylint.pycqa.org/en/latest/user_guide/messages/warning/implicit-str-concat.html
This fixes the string formatting to avoid the warning.
=> Fix pylint implicit-str-concat

.github/workflows/soco-check-jobs.yaml, README.rst, requirements-dev.txt, setup.py
Python 3.5 has been considered EOL since September 2020 and `requests` (a primary dependency) has dropped support as of [2.26.0](https://docs.python-requests.org/en/latest/community/updates/#id1). This removes a workaround for handling `black` in the CI.
Dropping support for 3.5 will allow use of some newer features, probably most visible being [f-strings](https://docs.python.org/3/reference/lexical_analysis.html#f-strings).
=> Remove Python 3.5 support

soco/core.py
This will pass through any kwargs provided to `add_to_queue`, `add_uri_to_queue`, and `add_multiple_to_queue` methods. The primary reason is to allow setting a (usually much longer) service `timeout` value per-call.
=> Pass kwargs to queue add service calls

requirements-dev.txt
This attempts to fix the CI by pinning a `flake8` dependency to an older version on py37.
=> Attempt to fix flake8 runs on 3.7

soco/music_services/accounts.py, soco/soap.py, soco/zonegroupstate.py
Note: the `# pylint: disable=W3101` statements should be removed as part of the completion of #925.
=> Additional pylint warning suppression

soco/music_services/accounts.py, soco/soap.py, tests/test_soap.py
Explicitly add the `timeout` parameter to the remaining `requests` calls.
A current bump to `pylint` (which is not currently pinned) added this check which is making CI runs fail.
=> Explicitly set default timeouts for remaining `requests` calls

soco/core.py
This PR adds the "Dolby Multichannel PCM 5.1" to the list of input formats SoCo can report on. 
Tested on a Beam Gen 2, input source was the Disney Plus.
=> Report "Dolby Multichannel PCM 5.1" input format

.github/workflows/soco-check-jobs.yaml
- Add Python "3.12.-dev" to the test matrix
- Add `libxml2-dev libxslt-dev python-dev` to the Linux package install list to install libxml successfully under 3.12-dev
=> Add Python 3.12-dev to the test matrix

soco/discovery.py
This resurrects and updates PR #644. It's a neat idea and avoids the requirement to use network scan discovery when multiple Sonos households are present on the network.
The PR adds an optional `household_id` parameter to `discover()`. If set, `discover()` will wait for a multicast discovery response that comes from a player in the selected household. If `allow_network_scan` is `True`, it will also use the selected household ID to filter responses.
Credit to @twosky2000 for the idea and initial implementation.
=> Allow standard multicast discovery to select by household_id

soco/discovery.py
On my networks I'm repeatedly finding that the default timeout of 0.1s when scanning the network for Sonos devices is too short to detect all devices reliably. Increasing the default timeout to 0.5s makes it significantly more reliable.
This only applies to the fallback `scan_network()` discovery method, not to any other network operations.
=> Increase 'scan_network' default timeout

soco/events_asyncio.py
The `events_asyncio` event handler did not explicitly mark `self.is_running = False` during listener shutdown. This would cause attempts to restart the listener to fail after it was previously stopped:
```python
Traceback (most recent call last):
...
sub = await soco.zoneGroupTopology.subscribe()
File "/usr/local/lib/python3.10/site-packages/soco/events_asyncio.py", line 373, in _async_wrap_subscribe
await subscribe(requested_timeout, auto_renew)
File "/usr/local/lib/python3.10/site-packages/soco/events_asyncio.py", line 506, in _async_make_request
response = await self.event_listener.session.request(
AttributeError: 'NoneType' object has no attribute 'request'
```
If the `is_running` attribute is false, this guard to avoid starting an already-running listener is incorrectly enforced: …
=> Mark `events_asyncio` handler as not running during stop

soco/data_structures.py, soco/discovery.py, soco/plugins/plex.py, soco/plugins/sharelink.py, soco/services.py, soco/soap.py, tests/test_services.py
This is just to handle error responses better, by throwing an UnknownSoCoException whenever an invalid xml_error response is received.
=> Handle UPnP error responses better

soco/alarms.py
I have added methods to more easily determine:
- The next `datetime` for an `Alarm`
- The next `datetime` for an `Alarms` (i.e. a whole zone/room)
These methods are particularly useful for home automation scenarios.
~~This is still a draft because I have not tested it yet.~~
Maybe there is a better name for the `bypass_disabled` argument?
=> Add methods to get next alarm datetime

soco/core.py
External 3rd party subwoofers can be used on Amp devices by using an RCA cable. Details here: https://support.sonos.com/en-us/article/use-a-third-party-subwoofer-with-amp-or-connect-amp.
This change unconditionally enables the `has_subwoofer` property for Amp devices as it's not clear how to detect this with current API methods. This enables the various subwoofer controls which are guarded by that property.
=> Unconditionally enable `has_subwoofer` on Amp devices

soco/core.py
Adds support for subwoofer crossover controls. As of now, I believe this only applies to Amp devices.
Connect:Amp devices have a non-adjustable crossover at 80hz. I assume this will report it properly and that attempts to change will have no effect. Unfortunately I do not have a Connect:Amp (or Amp) to test with.
=> Add `sub_crossover` controls

soco/events_base.py, soco/zonegroupstate.py
A followup to the ZoneGroupState caching added in https://github.com/SoCo/SoCo/pull/913.
The last `ZoneGroupState` payload received for a Sonos system can be used indefinitely as long as a `ZoneGroupTopology` subscription remains active. With long-lived subscriptions, idle devices will have periods of time where no ZoneGroupState payload is published and the ZGS cache (60s since the last "event") will usually expire long before the subscription needs to be renewed. After it expires, it requires a poll to request a fresh payload and on large systems this will fail (see https://github.com/SoCo/SoCo/pull/937).
Instead of extending the ZGS cache by 60s every time a subscription event is received, this keeps the cache alive while _any_ `ZoneGroupTopology` subscription remains active. This …
=> Cache ZoneGroupState while subscriptions are active

soco/core.py
The new Arc Ultra devices identify themselves as "Sonos Arc Ultra". This adds support for the soundbar-related controls.
=> Add Arc Ultra support

soco/core.py, tests/data/media_metadata_payloads/tunein.json
When a radio station provides track metadata using TYPE=SNG in the stream_content and the album name contains a hyphen the track title, artist and album would not be parsed correctly.
The fix is to check for TYPE=SNG first; rather than the presence of a hyphen.
Reference HA issue:  https://github.com/home-assistant/core/issues/136474
=> Parse hyphens in track metadata

soco/core.py
Hello everyone,
This is my first participation in this repo !
In short: I added the missing audio format "Dolby Digital Plus 7.1".
In detail, I added the Sonos integration in Home Assistant, and while watching a movie, I noticed that "Unknown audio input format: 118489146" was displayed in HA (using the Sonos Arc Ultra with surround speakers):
In the Sonos app, the audio format displayed was "Dolby Digital Plus 7.1":
So I added the missing audio format ID in the audio formats list.
Thank you for your consideration for this PR !
Best regards from Switzerland 🇨🇭 !
=> Added the missing audio format "Dolby Digital Plus 7.1"

soco/__init__.py, soco/core.py, tests/test_core.py
In the Arc Ultra Soundbar, Sonos has changed the interface for enabling / disabling dialog mode.
SpeechEnhanceEnabled property (new for SoCo) is used to enable / disable dialog mode
DialogLevel (existing) is a multistate property with values 1,2,3,4 to control the dialog level (Low, Medium, High, Max)
For other model soundbars DialogLevel is used to turn on / off dialog mode and does not use SpeechEnhanceEnabled 
https://github.com/home-assistant/core/issues/142881
=> Arc Ultra Soundbar SpeechEnhanceEnabled property
