SoCo/SoCo

doc/conf.py, requirements-dev.txt
=> Use Napoleon sphinx module for nicer docstrings

README.rst
Just a couple of fixes to the README file - including a syntax error in the code sample.
=> Small README fixes

soco/data_structures.py
Adds and extra Sonos favorite class. Fixes #301 and tested there.
=> Audio broad cast sonos favorite

examples/play_local_files/play_local_files.py
One of the more frequently asked questions is how to play local files. While, as far as I know, it is not possible in the sense that we have found no interface to stream data to the units, we can cheat and just setup a temporary http server with python.
This example shows how, and plays a random file from the current folder on a named Sonos unit.
=> Added play_local_files example

MANIFEST.in, makefile
Added a few useful Makefile targets, and improved the Manifest.in file to ensure that tests, examples etc are included in the source dist
=> More make targets, and better sdists

dev_tools/sonosdump.py
I use this tool to find out what services are available. It is probably sufficiently useful to be included
=> Adding sonosdump tool

soco/core.py, tests/test_core.py, tests/test_integration.py
Tests written both in test_core using moco and in test_integrations against a device. Closes issue #341.
=> Added remove_sonos_playlist function. 

soco/music_services/music_service.py, tests/test_musicservices.py
Helpful methods for constructing playable items from music service track ids.  See:
https://gist.github.com/lawrenceakka/2d21dca590b4fa7e3af2
=> A few more useful methods in MusicService

AUTHORS.rst, soco/core.py, soco/data_structures.py, tests/test_integration.py
Add base method reorder_sonos_playlist and a number of helpers, documentation and tests.
=> Major PR for Sonos Playlist Management.

soco/music_library.py
Fix call to soco.contentDirectory() if soco=None in MusicLibrary()
=> Fix MusicLibrary constructor.

soco/core.py
Simple doc string fix inspired by #389. Posted as PR for reference.
=> Explain current_info on slave in dosctring

soco/discovery.py, tests/test_discovery.py
An updated version of #289 and #292
=> More aggressive discovery

soco/discovery.py
Fix for issue #418. Just posted as PR for complete tests.
=> Made config import relative, fixes #418

soco/core.py
Added a timeout option to ‘requests’ while getting speaker info.
=> Timeout request

soco/core.py
Added `get_sonos_favorites(self, start=0, max_items=100)`.
Fixed `get_favorite_radio_shows(self, start=0, max_items=100)`.
=> Added support for getting Sonos Favorites.  Fixed some bugs with getting Radio Shows

doc/examples.rst, soco/data_structures.py
A have added a few queue related examples to the micro examples page.
Let me know what you think.
=> Added a few queue micro examples

soco/core.py
This is a fix for #485.
`add_multiple_to_queue()` now breaks the list into chunks of 16 items and makes separate requests to add each one to the queue.
Multiple requests, however, means that we cannot return the 'index at which the items were enqueued' anymore, so I have removed the return value (I cannot see much value in knowing the position at which the first of many items was enqueued anyway).
=> Fix add_multiple_to_queue fails with too many items

soco/data_structures_entry.py
This error message shows up frequently for me but it appears to not be an error at all.
=> Decrease logging level

soco/data_structures.py, soco/events.py
Closes  #453.
Code was copied from @bosim's PR, so credit goes to him.
=> Handle none values, the 2nd

soco/data_structures.py
Added clarification on the roles of `DidlFavorite` and its `reference`.
=> Small addition to DidlFavorite docstring

soco/core.py
Lots of core.py docstrings, reformatted into Napoleon style.
=>  Major docstring fixes and reformats (Napoleon Style FTW!) 

examples/play_local_files/play_local_files.py
It seems that the play_local_files script is popular, but also that people have issues with it. This PR does two things:
* Fixes the index bug mentioned in #508
* Improves the script by:
* Replacing in-script configuration with command line configuration
* Try and autodetect the local IP-address of the machine
* Perform more checking when trying to get the zone
Closes #508.
=> Revision of play_local_files script

README.rst
The development of SoCo has progressed a lot, but the readme page has not been kept up to date.
This PR adds some of the newer additions to README.rst in the 'Features' section.
=> Update the feature list in the readme

soco/core.py, tests/test_core.py
Fix support for Playbar, and add for Playbase and Beam.
Fix #633
=> Add is_soundbar property and support all soundbars

soco/core.py
Properly parse discover return messages. Addresses 
https://github.com/SoCo/SoCo/issues/660
=> Fix for Issue 660 - Properly parse discover

requirements-dev.txt, setup.cfg, soco/cache.py, soco/core.py, soco/data_structures.py, soco/ms_data_structures.py, soco/music_services/accounts.py, soco/music_services/data_structures.py, soco/services.py
This makes the build pass again.
Handles #647 by ignoring W504 until a decision is made.
=> Travis fixes

doc/advanced/events.rst, doc/advanced/events_twisted.rst, doc/api/soco.events.rst, soco/config.py, soco/events.py, soco/events_base.py, soco/events_twisted.py, soco/services.py, tests/test_events.py
This is version 2, implementing suggestions by @KennethNielsen and @ghcs27. See #575 for discussion.
I propose to update this pull request to address #590 [DONE]. 
Let me know if there is anything else I should incorporate.
=> In events module: allow choice in how the event server is implemented (v2)

soco/core.py, tests/test_core.py
This is a PR for the functionality discussed in https://github.com/SoCo/SoCo/issues/692. Credit to https://github.com/tephlon for the idea and the majority of the implementation.
=> Add operations to get/set the speaker balance

soco/discovery.py
Fix iteration bug i discover.py
=> Avoid trying to iterate a None

tests/test_music_library.py
This minor PR just adds a missing unit test.
=> Add unit test for SoCo.MusicLibrary.delete_music_share().

examples/webapp/index.py
There is an error when trying to run this code: TypeError: Unicode-objects must be encoded before hashing. I added the code to fix that issue.
=> Fixing error in index.py so it will run.

doc/releases/0.19.rst, doc/releases/index.rst
Pull request for 0.19 release notes. The PR is made just to make sure all the tests pass on Travis before tagging the release.
=> 0.19 release notes

soco/core.py
Add the value "arc" to SOUNDBARS for "soundbar product names"
=> Update core.py to recognize "arc" as a soundbar

soco/events.py
Merged downstream as https://github.com/amelchio/pysonos/pull/60
Resolves https://github.com/home-assistant/core/issues/36183
If port 1400 is unavailable, try the next 100 ports
in order to match the behavior in events_twisted.
When multiple Home Assistant instances are running on
the same server, sonos was falling back to polling.  As
support is already available for trying the next port
in events_twisted, this functionality is now extended
to events.
=> Make events match events_twisted behavior when port 1400 is unavailable.

requirements-dev.txt, soco/__init__.py, soco/core.py, soco/data_structures.py, soco/discovery.py, soco/events.py, soco/events_base.py, soco/events_twisted.py, soco/groups.py, soco/ms_data_structures.py, soco/music_library.py, soco/services.py, soco/utils.py, tests/soco_unittest.py, tests/test_core.py, tests/test_integration.py, tests/test_music_library.py
This removes the version pin for Black used in the checks, and updates the formatting of all affected files.
=> Unpin Black version and apply formatting changes

soco/snapshot.py
The fixed volume setting (on e.g. the Connect) also fixes the equalization settings so we should not try to restore those.
=> Do not try to restore bass/treble/loudness with fixed volume

setup.py
- Update the supported Python versions
- Change `Development Status` to `4 - Beta`
- Apply Black formatting
- Add python_requires=">=3.5"
=> Updates to 'setup.py' for the 0.21 release

.github/workflows/check-jobs.yaml, .github/workflows/soco-check-jobs.yaml
This is temporary until we have a cleaner, tox-based configuration.
=> Add brute force Github Actions check jobs until tox config arrives

doc/examples.rst
=> Add group manipulation example to micro examples

soco/plugins/__init__.py, tests/conftest.py
Fixes a couple of very minor docstring nits raised by an updated version
of Black.
=> Address minor Black issues

soco/events_asyncio.py
=> Fix manual subscription renewals and unsubscibe failure handling with asyncio

soco/events_asyncio.py
Upstream of https://github.com/amelchio/pysonos/pull/82 to fix https://github.com/home-assistant/core/issues/49954
=> Fix race condition in creating the client session

soco/discovery.py
This adds a small function to the discovery module, to filter out non-contactable speakers. See the discussion in #828 for motivation.
=> Add 'contactable()' function to filter out non-accessible speakers

soco/discovery.py
Reduces numerous INFO level logging statements to DEBUG.
Increases two INFO level logging statements to WARN.
Relevant to #792.
=> Adjust logging severities in discovery module

soco/data_structures_entry.py, soco/events_asyncio.py, soco/music_services/data_structures.py
A followup to #835 to improve logging. Mostly based on what I've encountered when running with Home Assistant.
The `data_structures_entry.py` change is my attempt to work around #599. Open to alternative solutions, of course.
=> More logging adjustments

soco/plugins/sharelink.py
@pwt I expect this to fix #847, can you please test?
It now hardcodes the service numbers and tries both US and global Spotify services in turn because there is apparently no reliable way to find the proper one.
=> Hardcode service numbers for ShareLink plugin

soco/core.py
Some radio stations provide place the URI (or a quoted URL string) in the `<dc:title>` element in the `avTransport.GetPositionInfo` response. In these cases, there is almost always a better value provided in the `<r:streamContent>` element.
Additionally, sometimes the `streamContent` data sometimes has extraneous whitespace padding. This trims the strings before saving.
Example "fixed" data returned by `SoCo.get_current_track_info()`:
```
{'album': '',
'album_art': '',
'artist': 'Oliver Wood',
'duration': '0:00:00',
'metadata': '<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" '
'xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" '
'xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" '
'xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item '
'id="-1" parentID="-1" …
```
=> Avoid using radio URIs as titles, trim whitespace

soco/discovery.py
- Close sockets opened for multicast discovery
- Fix logic for 'allow_network_scan' fallback
- Additional DEBUG logging
=> Improvements to 'discover()'

soco/plugins/sharelink.py
User-created playlists have a slightly different URL format, I've extended the regexp to support them as well.
=> ShareLink: Apple Music: Support user-created playlists

soco/core.py
Adds home theater control support for the new Ray device.
=> Add Ray to known soundbars

requirements-dev.txt, soco/zonegroupstate.py
=> Add error message/details for failure to import 'lxml'
